
// Auto-generated by Firefoo v1.5.11 on 2024-07-15 21:48:33 UTC

export interface File {
    comment:       string;
    date:          string;
    downloadURL:   string;
    id:            string;
    invoiceNumber: string;
    status?:       string;
    type:          string;
    user:          string;
    userEmail:     string;
    userName:      string;
  }
  