// Auto-generated by Firefoo v1.5.11 on 2024-07-15 21:48:49 UTC

export interface Homologation {
  
    createdAt:                     string;
    homologationFactor?:           number | null;
    homologationIngredientId?:     null | string;
    homologationIngredientName?:   null | string;
    homologationPriceByUdm:        number;
    homologationQtyByUdm:          number;
    homologationSubTotal:          number;
    homologationType:              string;
    homologationUdm?:              null | string;
    id:                            string;
    ingredientDiscountAmount:      number;
    ingredientSupplierCode:        string;
    ingredientSupplierDescription: string;
    ingredientSupplierName:        string;
    ingredientSupplierQty:         number;
    ingredientSupplierSubTotal:    number;
    ingredientSupplierUdm:         string;
    ingredientSupplierUnitPrice?:  number;
    invoiceDate:                   string;
    invoiceDiscounts:              number;
    invoiceDiscountsRef:           unknown;
    invoiceId:                     number;
    invoiceLineId:                 string;
    invoicePeriod:                 string;
    invoiceShippingAmount:         number;
    invoiceSupplierDNI:            string;
    invoiceSupplierFantasyName:    string;
    invoiceSupplierName:           string;
    invoiceTotal:                  string;
    shippingAmount:                number;
  }
  