// Auto-generated by Firefoo v1.5.11 on 2024-07-15 21:49:07 UTC

/**
 * @name - Ingredient
 * @param active - ??boolean
 * @param ingredientType {string | 'premade' | 'rawMaterial'} -
 * @param premadeMaterialData {premadeMaterialData[]} -  - Solamente estaría activo si es que ingredientType es premade
 *
 * @summary Solamente estaría activo si es que ingredientType es premade
 */
export interface Ingredient {
  active: number;
  alert?: boolean;
  costCategory: CostCategory;
  createdAt?: string;
  createdBy?: CreatedBy;
  desc?: null | string;
  hierarchy?: null | string;
  homologatedWords?: string[];
  id: string;
  isPotentialSavings?: boolean;
  minStock?: null;
  name: string;
  toteatId: string;
  udmConteo?: UdmConteo[];
  unity: string;
  ingredientType: string | "premade" | "rawMaterial";
  premadeMaterialData: premadeMaterialData[];
}

export interface premadeMaterialData {
  /**
   * @name ingredientId
   * @description Id del ingrediente
   */
  ingredientId: string;
  qty: number;
  udm: string; // este id no está definido en ningún lado
}

export interface CostCategory {
  id: string;
  name: string;
}

export interface CreatedBy {
  id: string;
  name: string;
}

export interface UdmConteo {
  convertion?: number;
  id: string;
  name: string;
  udmBase: string;
}
