
// Auto-generated by Firefoo v1.5.11 on 2024-07-15 21:49:20 UTC

export interface Storagerequest {
    createdAt:     string;
    createdBy:     string;
    createdByName: string;
    id:            string;
    items:         Item[];
    number:        number;
    pdfpath:       string;
    status:        string;
  }
  
  export interface Item {
    id:    string;
    name:  string;
    qty:   number;
    unity: string;
  }
  